name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project from ZIP
        run: |
          unzip -o POTOTIME-Android-GHA.zip
          # jika ZIP mengekstrak folder, pindahkan isinya ke root
          shopt -s dotglob || true
          if [ -d POTOTIME-Android-GHA ]; then mv -f POTOTIME-Android-GHA/* . ; fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target: android-34
          components: build-tools;34.0.0

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: |
            :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: POTOTIME-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
