# .github/workflows/build-from-zip.yml
name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project from ZIP
        run: |
          unzip -o POTOTIME-Android-GHA.zip -d extracted
          # kalau hasil unzip berupa folder, pindahkan isinya ke root
          if [ -d extracted/POTOTIME-Android-GHA ]; then
            rsync -a extracted/POTOTIME-Android-GHA/ ./
          else
            rsync -a extracted/ ./
          fi
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          components: build-tools;34.0.0

      # Proyek kamu belum punya ./gradlew, jadi install Gradle 8.7 manual
      - name: Install Gradle 8.7
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v

      - name: Build (assembleDebug)
        run: gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: POTOTIME-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
